### PR TITLE
Fix mock prover performance regression for lookup arguments

### LINKED ISSUE #398: [MockProver] Testing is slower after #389
### Problem

The test speed is slower when #389 is applied.

We use the test of this branch for experiment https://github.com/appliedzkp/zkevm-circuits/pull/156

`cargo test --release test_rho_gate -p keccak256  -- --nocapture` is about 11 sec on old commit `4283713e`, but is about 34 sec on `1723fed1`, which is `4283713e` with `git cherry-pick b94aab76a338870fec778d4da3a1c6789bc92bc4`.

The hardware is the apple M1 silicon.

### Solution

Need investigation

### PR DESCRIPTION
**Pull request by daira**
closes #398

Signed-off-by: Daira Hopwood <daira@jacaranda.org>

### CODE REVIEW

**Comment by daira** [comment]
I recommend to review ignoring whitespace changes.

File: src/dev.rs [hunk 1]
```diff
@@ -835,90 +835,128 @@ impl<F: FieldExt> MockProver<F> {
...
+                        .iter()
+                        .filter_map(move |(input, input_row)| {
+                            let input_row = *input_row;
+                            while i < table.len() && &table[i] < input {
+                                i += 1;
+                            }
+                            if i == table.len() || &table[i] > input {
+                                assert!(table.binary_search(input).is_err());
+
+                                let input_columns = calc_input_columns();
```
Comment (daira) [inline src/dev.rs:924]: This doesn't depend on the input row so we could cache it, but that's a separate optimization, and would only affect the case where we have lots of lookup failures.

File: src/dev.rs [hunk 2]
```diff
@@ -835,90 +835,128 @@ impl<F: FieldExt> MockProver<F> {
...
+                                println!("Lookup input columns: {:?}", &input_columns);
```
Comment (ebfull) [inline src/dev.rs:925]: Remove this print statement.

**Review by ebfull — CHANGES_REQUESTED** [review]

File: src/dev.rs (hunk 2 above)
Comment (daira) [reply src/dev.rs:925]:
```suggestion
```

**Comment by str4d** [comment]
This will conflict with #433; I'd prefer to merge that PR before this one, in part because it will simplify the diff here.

File: src/dev.rs [hunk 3]
```diff
@@ -835,90 +835,127 @@ impl<F: FieldExt> MockProver<F> {
                         )
                     };
 
+                    assert!(lookup.table_expressions.len() == lookup.input_expressions.len());
+                    let zeros = vec![Value::Real(F::zero()); lookup.table_expressions.len()];
+                    let mut table_has_zeros = false;
```
Comment (therealyingtong) [inline src/dev.rs:840]: I suspect that the `table_has_zeros` case will be less common after #448.

**Review by therealyingtong — APPROVED** [review]
utACK with comments.

**Comment by daira** [comment]
Changing this back to draft because I need to change it to optimize fill rows rather than zero rows.

File: halo2_proofs/src/dev.rs [hunk 4]
```diff
@@ -914,40 +914,86 @@ impl<F: FieldExt> MockProver<F> {
...
+                            }
+                        })
+                        .collect();
+                    inputs.sort_unstable();
+
+                    let mut i = 0;
+                    inputs
+                        .iter()
+                        .filter_map(move |(input, input_row)| {
+                            let input_row = *input_row;
```
Comment (daira) [inline halo2_proofs/src/dev.rs:976]:
```suggestion
```

File: halo2_proofs/src/dev.rs [hunk 5]
```diff
@@ -914,40 +914,86 @@ impl<F: FieldExt> MockProver<F> {
...
+                            }
+                            if i == table.len() || &table[i] > input {
+                                assert!(table.binary_search(input).is_err());
+
+                                Some(VerifyFailure::Lookup {
+                                    lookup_index,
+                                    location: FailureLocation::find_expressions(
+                                        &self.cs,
+                                        &self.regions,
+                                        input_row,
```
Comment (daira) [inline halo2_proofs/src/dev.rs:988]:
```suggestion
                                        *input_row,
```

**Review by daira — COMMENTED** [review]
Minor simplification.

**Comment by daira** [comment]
This is still up-to-date and needs review.

File: halo2_proofs/src/dev.rs [hunk 6]
```diff
@@ -915,8 +915,18 @@ impl<F: FieldExt> MockProver<F> {
                     };
 
                     assert!(lookup.table_expressions.len() == lookup.input_expressions.len());
-                    let fill_row = vec![Value::Real(F::zero()); lookup.table_expressions.len()];
-                    let mut table_has_fill_row = false;
+                    assert!(self.usable_rows.end > 0);
+
+                    // We optimize on the basis that the last usable row might have been repeated to fill
+                    // the table (it doesn't matter if it wasn't). Note that this "fill row" necessarily
```
Comment (str4d) [inline halo2_proofs/src/dev.rs:921]: This doesn't match what we actually do in either `SimpleFloorPlanner` or `floor_planner::V1`, which is to use the _first_ row of the table assignment as the fill row:

https://github.com/zcash/halo2/blob/221766986b52d2a35f60d94266647d9dcf908231/halo2_proofs/src/circuit/floor_planner/single_pass.rs#L437-L444

As you say, it doesn't really matter; the performance improvement we observe is not due to this optimisation.

**Review by str4d — APPROVED** [review]
ACK; I observe the desired speed-up.

File: halo2_proofs/src/dev.rs (hunk 6 above)
Comment (daira) [reply halo2_proofs/src/dev.rs:921]: This is a misunderstanding of the comment. Whichever policy was used to pick the fill row, provided that there were any fill rows, the table contents after filling will have the contents of the fill row in the last usable row. (If there were no fill rows, treating the last usable row as the potential fill contents is still harmless.)

File: halo2_proofs/src/dev.rs [hunk 7]
```diff
@@ -914,40 +914,85 @@ impl<F: FieldExt> MockProver<F> {
...
                     };
 
+                    assert!(lookup.table_expressions.len() == lookup.input_expressions.len());
+                    assert!(self.usable_rows.end > 0);
+
+                    // We optimize on the basis that the last usable row might have been repeated to fill
+                    // the table (it doesn't matter if it wasn't). Note that this "fill row" necessarily
+                    // exists in the table, and we use that fact to slightly simplify the optimization:
+                    // we're only trying to check that all input rows are contained in the table, and so
+                    // we can safely just drop input rows that match the fill row.
```
Comment (daira) [inline halo2_proofs/src/dev.rs:924]:
```suggestion
                    // We optimize on the basis that the table might have been filled so that the last
                    // usable row now has the fill contents (it doesn't matter if there was no filling).
                    // Note that this "fill row" necessarily exists in the table, and we use that fact to
                    // slightly simplify the optimization: we're only trying to check that all input rows
                    // are contained in the table, and so we can safely just drop input rows that
                    // match the fill row.
```

**Review by str4d — APPROVED** [review]
re-utACK b48b032041d74a6ac6148d72f9b44b8f52972192
