### PR TITLE
Only allow fixed queries at `Rotation::cur`

### LINKED ISSUE #585: Prohibit queries of fixed columns at non-cur rotations.
Rationale: There's [a technique](https://hackmd.io/@dJO3Nbl4RTirkR2uDM6eOA/BkoOdpwFF) that lets us make fixed columns almost free inside of recursion, which works ideally when fixed columns are not queried at non-cur rotations. I can't think of a situation where we would query a fixed column at an offset though? If we prohibited these queries entirely in the API, we could assume within recursion that we can deploy this trick.

### PR DESCRIPTION
**Pull request by therealyingtong**
Closes #585.

### CODE REVIEW

**Review by daira — APPROVED** [review]
utACK

File: halo2_proofs/src/plonk/circuit.rs [hunk 1]
```diff
@@ -1169,17 +1169,18 @@ impl<F: Field> ConstraintSystem<F> {
         panic!("get_instance_query_index called for non-existent query");
     }
 
-    pub(crate) fn get_any_query_index(&self, column: Column<Any>, at: Rotation) -> usize {
+    pub(crate) fn get_any_query_index(&self, column: Column<Any>) -> usize {
```
Comment (str4d) [inline halo2_proofs/src/plonk/circuit.rs:1172]: Is this really only used to query at `Rotation::cur()`? If so, we should document it as such.

**Review by str4d — APPROVED** [review]
ACK 41c87eac0f9766dc36af94291ae8537581b1272b. I confirmed that the `orchard` circuit is unaltered.

**Review by ebfull — APPROVED** [review]
